#!/usr/bin/env bash
set -Eeuo pipefail

# Detach from Coder pipes
exec </dev/null >/dev/null 2>&1

# These directories are assumed by PGAdmin via Dockerfile ENV Vars
mkdir -p \
 /home/coder/data \
 /home/coder/logs \
 /home/coder/data/pgadmin \
 /home/coder/data/pgadmin/sessions \
 /home/coder/data/pgadmin/storage 

sudo chown -R coder:coder /home/coder/data  
 
# Use the configured storage dir from env (falls back to the project default)
PGADMIN_STORAGE_DIR="${PGADMIN_CONFIG_STORAGE_DIR:-/home/coder/data/pgadmin/storage}"
mkdir -p "$PGADMIN_STORAGE_DIR"
sudo chown -R coder:coder "$PGADMIN_STORAGE_DIR"

SERVERS_FILE="$PGADMIN_STORAGE_DIR/servers.json"

# Write a servers.json only if it doesn't exist yet (so we don't overwrite user changes)
if [ ! -f "$SERVERS_FILE" ]; then
  cat > "$SERVERS_FILE" <<EOF
{
  "Servers": {
    "1": {
      "Name": "Workspace Postgres",
      "Group": "Local",
      "Host": "${POSTGRES_HOST:-127.0.0.1}",
      "Port": ${POSTGRES_PORT:-5432},
      "MaintenanceDB": "${POSTGRES_DB:-postgres}",
      "Username": "${POSTGRES_USER:-coder}",
      "SSLMode": "prefer",
      "Comment": "Auto-generated by startup",
      "PasswordExecCommand": "printenv POSTGRES_PASSWORD"
    }
  }
}
EOF
  sudo chown coder:coder "$SERVERS_FILE"
  sudo chmod 600 "$SERVERS_FILE"
fi 

#  Cleanup pgadmin state 
if [ -f "/home/coder/data/pgadmin/pgadmin.db" ] && [ ! -f "/home/coder/data/pgadmin/.desktop_init_done" ]; then
  rm -f "/home/coder/data/pgadmin/pgadmin.db"
  rm -rf "/home/coder/data/pgadmin/sessions"/*
  touch "/home/coder/data/pgadmin/.desktop_init_done"
fi
 
# Gate admin HTTP to enrich links later (best-effort)
for i in $(seq 1 10); do
  curl -fsS http://localhost:9000/ >/dev/null 2>&1 && break
  sleep 1
done

# Start pgAdmin if not already listening
if ! lsof -ti :5050 >/dev/null 2>&1; then
  if command -v pgadmin4 >/dev/null 2>&1; then
    setsid sh -c 'exec pgadmin4 >> /home/coder/logs/pgadmin4.out 2>&1' </dev/null >/dev/null 2>&1 &
  elif [ -x "/opt/pgadmin-venv/bin/pgadmin4" ]; then
    setsid sh -c 'exec /opt/pgadmin-venv/bin/pgadmin4 >> /home/coder/logs/pgadmin4.out 2>&1' </dev/null >/dev/null 2>&1 &
  fi
fi

exit 0
